a. Search Internet and find a structured dataset for binary classification. Clearly identify input(s) and output(s).
b. Use a 1-hidden layer NN and implement your own code in Python to train and test it (with adequate epoch number). Use Adam optimizer (beta_1=0.9, beta_2=0.999) and a fixed learning rate. Use at least three different number of neurons in the hidden layer and at least three batch sizes and compare the results by preparing confusion matrix and related metrics.

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
dataFrame = pd.read_csv("https://raw.githubusercontent.com/DogukanOzyurt/DiabetesBinaryClassification./main/DiabetesBinaryClassification.csv")

In [ ]:
dataFrame

Number of times pregnant  \
0                           6   
1                           1   
2                           8   
3                           1   
4                           0   
..                        ...   
763                        10   
764                         2   
765                         5   
766                         1   
767                         1   

     Plasma glucose concentration a 2 hours in an oral glucose tolerance test  \
0                                                  148                          
1                                                   85                          
2                                                  183                          
3                                                   89                          
4                                                  137                          
..                                                 ...                          
763                                                101                          
764                                                122                          
765                                                121                          
766                                                126                          
767                                                 93                          

     Diastolic blood pressure (mm Hg)  Triceps skin fold thickness (mm)  \
0                                  72                                35   
1                                  66                                29   
2                                  64                                 0   
3                                  66                                23   
4                                  40                                35   
..                                ...                               ...   
763                                76                                48   
764                                70                                27   
765                                72                                23   
766                                60                                 0   
767                                70                                31   

     2-Hour serum insulin (mu U/ml)  \
0                                 0   
1                                 0   
2                                 0   
3                                94   
4                               168   
..                              ...   
763                             180   
764                               0   
765                             112   
766                               0   
767                               0   

     Body mass index (weight in kg/(height in m)^2)  \
0                                              33.6   
1                                              26.6   
2                                              23.3   
3                                              28.1   
4                                              43.1   
..                                              ...   
763                                            32.9   
764                                            36.8   
765                                            26.2   
766                                            30.1   
767                                            30.4   

     Diabetes pedigree function  Age (years)  Class variable (0 or 1)  
0                         0.627           50                        1  
1                         0.351           31                        0  
2                         0.672           32                        1  
3                         0.167           21                        0  
4                         2.288           33                        1  
..                          ...          ...                      ...  
763                       0.171           63                        0  
764                       0.

In [ ]:
number_of_inputs = 8
train_split = 0.8
val_split = 0.1
test_split = 0.1
iodataset = dataFrame.values
np.random.shuffle(iodataset)

In [ ]:
iodataset

array([[  8.   , 118.   ,  72.   , ...,   1.476,  46.   ,   0.   ],
       [  4.   , 141.   ,  74.   , ...,   0.244,  40.   ,   0.   ],
       [  2.   , 112.   ,  75.   , ...,   0.148,  21.   ,   0.   ],
       ...,
       [  7.   , 114.   ,  76.   , ...,   0.466,  31.   ,   0.   ],
       [  0.   , 102.   ,  78.   , ...,   0.238,  24.   ,   0.   ],
       [  9.   , 134.   ,  74.   , ...,   0.46 ,  81.   ,   0.   ]])

In [ ]:
indices_or_sections = [int(train_split * len(dataFrame)), int((1 - test_split) * len(dataFrame))]
train_set, val_set, test_set = np.split(iodataset, indices_or_sections)
np.set_printoptions(suppress=True)
print("Train set size: ", len(train_set))
print("Validation set size: ", len(val_set))
print("Test set size: ", len(test_set))
x_train = train_set[:,0:number_of_inputs]
y_train = train_set[:,number_of_inputs]
x_val = val_set[:,0:number_of_inputs]
y_val = val_set[:,number_of_inputs]
x_test = test_set[:,0:number_of_inputs]
y_test = test_set[:,number_of_inputs]

Train set size:  614
Validation set size:  77
Test set size:  77


In [ ]:
x_train

array([[  8.   , 118.   ,  72.   , ...,  23.1  ,   1.476,  46.   ],
       [  4.   , 141.   ,  74.   , ...,  27.6  ,   0.244,  40.   ],
       [  2.   , 112.   ,  75.   , ...,  35.7  ,   0.148,  21.   ],
       ...,
       [  1.   , 117.   ,  88.   , ...,  34.5  ,   0.403,  40.   ],
       [  3.   ,  74.   ,  68.   , ...,  29.7  ,   0.293,  23.   ],
       [  1.   , 139.   ,  46.   , ...,  28.7  ,   0.654,  22.   ]])

In [ ]:
y_train

array([0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0.,
       1., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1.,
       0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0.,
       1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1.,
       0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1.,
       1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0.

In [ ]:
import numpy as np

class my_NN(object):
    def __init__(self):
        self.input = 8  # feature numbers
        self.output = 1  # class number
        self.hidden_units = 4

        # initialize matrix of weights
        np.random.seed(1)
        # weight1: input = hidden layer
        self.w1 = np.random.randn(self.input, self.hidden_units)
        # weight2: hidden layer = output
        self.w2 = np.random.randn(self.hidden_units, self.output)

    def _normalize(self, x):
        # Min-Max normalization to [0, 1] range
        return (x - np.min(x)) / (np.max(x) - np.min(x))

    # forward_propagation
    def _forward_propagation(self, x_train):
        # Normalize
        normalized_x_train = self._normalize(x_train)

        self.z2 = np.dot(self.w1.T, normalized_x_train.T)
        self.a2 = self._sigmoid(self.z2)
        self.z3 = np.dot(self.w2.T, self.a2)
        self.a3 = self._sigmoid(self.z3)
        return self.a3

    def _sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def _loss(self, predict, y_train):
        m = y_train.shape[0]
        logprobs = np.multiply(np.log(predict), y_train) + np.multiply((1 - y_train), np.log(1 - predict))
        loss = -np.sum(logprobs) / m
        return loss

    # backpropagation
    def _backward_propagation(self, x_train, y_train):
        predict = self._forward_propagation(x_train)
        m = x_train.shape[0]
        delta3 = predict - y_train
        dz3 = np.multiply(delta3, self._sigmoid_prime(self.z3))
        self.dw2 = (1 / m) * np.sum(np.multiply(self.a2, dz3), axis=1).reshape(self.w2.shape)

        delta2 = delta3 * self.w2 * self._sigmoid_prime(self.z2)
        self.dw1 = (1 / m) * np.dot(x_train.T, delta2.T)

    def _sigmoid_prime(self, z):
        return self._sigmoid(z) * (1 - self._sigmoid(z))

    def _update(self, learning_rate=0.01):
        self.w1 = self.w1 - learning_rate * self.dw1
        self.w2 = self.w2 - learning_rate * self.dw2

    def train(self, x_train, y_train, iteration=10):
        for i in range(iteration):
            y_hat = self._forward_propagation(x_train)
            loss = self._loss(y_hat, y_train)
            self._backward_propagation(x_train, y_train)
            self._update()
            if i % 10 == 0:
                print("loss: ", loss)

    def predict_proba(self, x_train):
        y_hat = self._forward_propagation(x_train)
        return y_hat.T

    def predict(self, x_train):
        y_hat_proba = self.predict_proba(x_train)
        return [1 if i[0] >= 0.5 else 0 for i in y_hat_proba]

    def score(self, predict, y_train):
        cnt = np.sum(predict == y_train)
        return (cnt / len(y_train)) * 100


if __name__ == '__main__':

    clr = my_NN()
    clr.train(x_train, y_train)
    pre_y_proba = clr.predict_proba(x_test)
    pre_y = clr.predict(x_test)
    # Accuracy
    score = clr.score(pre_y, y_test)

    print('Predicted Probabilities: ', pre_y_proba)
    print('Predicted Classes: ', pre_y)
    print('True Classes: ', y_test)
    print('Accuracy Score: ', score)


loss:  0.6628727252658018
Predicted Probabilities:  [[0.25518369]
 [0.25010401]
 [0.26027761]
 [0.25123261]
 [0.25428564]
 [0.25755093]
 [0.24950445]
 [0.27595455]
 [0.25999999]
 [0.24954597]
 [0.24452188]
 [0.25160359]
 [0.25052837]
 [0.25137543]
 [0.25533472]
 [0.25378288]
 [0.263604  ]
 [0.2532764 ]
 [0.2533063 ]
 [0.26447501]
 [0.25033154]
 [0.25109543]
 [0.25099173]
 [0.2506502 ]
 [0.29374621]
 [0.30741852]
 [0.27091961]
 [0.25400306]
 [0.25075969]
 [0.24954245]
 [0.25108685]
 [0.25440562]
 [0.26697874]
 [0.25156245]
 [0.25882479]
 [0.26074258]
 [0.25040014]
 [0.25961407]
 [0.25353783]
 [0.25485287]
 [0.25360437]
 [0.25396673]
 [0.25178548]
 [0.26161839]
 [0.25039612]
 [0.25328268]
 [0.27572207]
 [0.27000611]
 [0.28536233]
 [0.24952192]
 [0.25833834]
 [0.26057997]
 [0.2526683 ]
 [0.25398707]
 [0.25355192]
 [0.264939  ]
 [0.24930387]
 [0.25054119]
 [0.25828075]
 [0.25612046]
 [0.2810204 ]
 [0.2501728 ]
 [0.25906173]
 [0.25007747]
 [0.25456039]
 [0.26337266]
 [0.25162853]
 [0.257347